version: '3.8'

# Suggested deployment command:
#  docker --host mega4.build.couchbase.com stack deploy --with-registry-auth -c sdk-jenkins-agents.yaml sdk
# All services, networks, etc. will then get an "sdk_" prefix,
# eg. "sdk_centos7"

# Default slave configuration. This is written using a YAML anchor so
# it can be substituted into all the slave declarations later. See
# https://medium.com/@kinghuang/docker-compose-anchors-aliases-extensions-a1e4105d70bd
x-default-jenkins-slave: &default-jenkins-slave
  init: true
  deploy:
    placement:
      constraints:
        - node.labels.role==build
    replicas: 2
  networks:
    - jenkins
  secrets:
    - source: ns-buildbot.rsa
      target: /home/couchbase/.ssh/ns-buildbot.rsa
      uid: '1000'
      gid: '1000'
      mode: 0400
    - source: id_ns-codereview_20181212
      target: /home/couchbase/.ssh/id_ns-codereview
      uid: '1000'
      gid: '1000'
      mode: 0400
    - source: sdk_docker_config_20210719
      target: /home/couchbase/.docker/config.json
      uid: '1000'
      gid: '1000'
      mode: 0400
    - source: sdk_jenkins_ns-buildbot_api_key.20220510
      target: /run/secrets/jenkins_master_password
  configs:
    - source: jenkins_master_username
      target: /run/secrets/jenkins_master_username
      mode: 0444
    - source: jenkins_slave_ssh_config_20200422
      target: /home/couchbase/.ssh/config
      uid: '1000'
      gid: '1000'
      mode: 0644


x-default-jenkins-slave-environment:
# Due to https://github.com/docker/compose/issues/229, the Jenkins container is
# created with a container name "sdk_jenkins", which is not a valid DNS entry.
# "dig" will actually resolve it OK inside another container, but Java will
# not, so we can't reference eg. "http://sdk_jenkins:8080/" as you would expect.
# To support CBD-3558 and any other cases where we need to build sdk-specific
# cbdeps packages, JENKINS_MASTER may be set in the local environment when
# running this stack. If it is, its value will override the value here. This
# means you can attach these agents temporarily to a different Jenkins master.
 - &default-jenkins-slave-environment-master "JENKINS_MASTER=${JENKINS_MASTER:-http://sdk-swarm.build.couchbase.com:8080/}"
 - &default-jenkins-slave-lang "LANG=en_US.UTF-8"
 - &repo-url "REPO_URL=https://github.com/couchbasedeps/git-repo"

services:

  alpine317:
    image: couchbasebuild/sdk-alpine3.17-build:20231103
    environment:
      - "JENKINS_SLAVE_NAME=build-alpine317"
      - "JENKINS_SLAVE_LABELS=sdk alpine3.17 alpine"
      - *default-jenkins-slave-environment-master
      - *default-jenkins-slave-lang
      - *repo-url
    <<: *default-jenkins-slave

  alpine318:
    image: couchbasebuild/sdk-alpine3.18-build:20231103
    environment:
      - "JENKINS_SLAVE_NAME=build-alpine318"
      - "JENKINS_SLAVE_LABELS=sdk alpine3.18 alpine"
      - *default-jenkins-slave-environment-master
      - *default-jenkins-slave-lang
      - *repo-url
    <<: *default-jenkins-slave

  # Placeholder for AWS agents
  # Note: this should always have zero replicas. Its presence here is
  # required to allow EC2 instances to discover the correct image.
  alpine-node-18-arm64:
    image: couchbasebuild/sdk-alpine-nodejs-18-build:20240724
    deploy:
      replicas: 0

  alpine-node-20-arm64:
    image: couchbasebuild/sdk-alpine-nodejs-20-build:20240724
    deploy:
      replicas: 0

  alpine-node-22-arm64:
    image: couchbasebuild/sdk-alpine-nodejs-22-build:20240724
    deploy:
      replicas: 0

  amzn2:
    image: couchbasebuild/sdk-amzn2-build:20230419
    environment:
      - "JENKINS_SLAVE_NAME=build-amzn2"
      - "JENKINS_SLAVE_LABELS=sdk amzn2"
      - *default-jenkins-slave-environment-master
      - *default-jenkins-slave-lang
      - *repo-url
    <<: *default-jenkins-slave

  centos7:
    image: couchbasebuild/sdk-centos7-build:20230419
    environment:
      - "JENKINS_SLAVE_NAME=build-centos7"
      - "JENKINS_SLAVE_LABELS=sdk centos7"
      - *default-jenkins-slave-environment-master
      - *default-jenkins-slave-lang
      - *repo-url
    <<: *default-jenkins-slave

  almalinux8:
    image: couchbasebuild/sdk-almalinux8-build:20231103
    environment:
      - "JENKINS_SLAVE_NAME=build-almalinux8"
      - "JENKINS_SLAVE_LABELS=sdk centos8 almalinux8"
      - *default-jenkins-slave-environment-master
      - *default-jenkins-slave-lang
      - *repo-url
    <<: *default-jenkins-slave

  debian9:
    image: couchbasebuild/sdk-debian9-build:20230419
    environment:
      - "JENKINS_SLAVE_NAME=build-debian9"
      - "JENKINS_SLAVE_LABELS=sdk debian9"
      - *default-jenkins-slave-environment-master
      - *default-jenkins-slave-lang
      - *repo-url
    <<: *default-jenkins-slave

  ubuntu20:
    image: couchbasebuild/sdk-ubuntu20-build:20230607
    environment:
      - "JENKINS_SLAVE_NAME=build-ubuntu20"
      - "JENKINS_SLAVE_LABELS=sdk ubuntu20 ubuntu20.04"
      - *default-jenkins-slave-environment-master
      - *default-jenkins-slave-lang
      - *repo-url
    <<: *default-jenkins-slave

  centos7-signing:
    image: couchbasebuild/sdk-centos7-signing:20220317
    environment:
      - "JENKINS_SLAVE_NAME=build-centos7-signing"
      - "JENKINS_SLAVE_LABELS=centos7-signing"
      - *default-jenkins-slave-environment-master
      - *repo-url
    <<: *default-jenkins-slave
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.role==build
    secrets:
      - source: sdk_signing_private_key.gpgkey
        uid: '1000'
        gid: '1000'
        mode: 0400
      - source: sdk_signing_public_key.gpgkey
        uid: '1000'
        gid: '1000'
        mode: 0400
      - source: ns-buildbot.rsa
        target: /home/couchbase/.ssh/ns-buildbot.rsa
        uid: '1000'
        gid: '1000'
        mode: 0400
      - source: id_ns-codereview_20181212
        target: /home/couchbase/.ssh/id_ns-codereview
        uid: '1000'
        gid: '1000'
        mode: 0400
      - source: sdk_jenkins_ns-buildbot_api_key.20220510
        target: /run/secrets/jenkins_master_password
    configs:
      - source: jenkins_master_username
        target: /run/secrets/jenkins_master_username
        mode: 0444
      - source: jenkins_slave_ssh_config_20200422
        target: /home/couchbase/.ssh/config
        uid: '1000'
        gid: '1000'
        mode: 0644

  debian10-signing:
    image: couchbasebuild/sdk-debian10-signing:20230309
    environment:
      - "JENKINS_SLAVE_NAME=build-debian10-signing"
      - "JENKINS_SLAVE_LABELS=debian10-signing docker"
      - *default-jenkins-slave-environment-master
      - *repo-url
    <<: *default-jenkins-slave
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.role==build
    secrets:
      - source: sdk_signing_private_key.gpgkey
        uid: '1000'
        gid: '1000'
        mode: 0400
      - source: sdk_signing_public_key.gpgkey
        uid: '1000'
        gid: '1000'
        mode: 0400
      - source: ns-buildbot.rsa
        target: /home/couchbase/.ssh/ns-buildbot.rsa
        uid: '1000'
        gid: '1000'
        mode: 0400
      - source: id_ns-codereview_20181212
        target: /home/couchbase/.ssh/id_ns-codereview
        uid: '1000'
        gid: '1000'
        mode: 0400
      - source: sdk_jenkins_ns-buildbot_api_key.20220510
        target: /run/secrets/jenkins_master_password
      - source: sdk_docker_config_20210719
        target: /home/couchbase/.docker/config.json
        uid: '1000'
        gid: '1000'
        mode: 0400
    configs:
      - source: jenkins_master_username
        target: /run/secrets/jenkins_master_username
        mode: 0444
      - source: jenkins_slave_ssh_config_20200422
        target: /home/couchbase/.ssh/config
        uid: '1000'
        gid: '1000'
        mode: 0644
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock


secrets:
  sdk_jenkins_ns-buildbot_api_key.20220510:
    external: true
  # SSH key which can read private GitHub repos
  ns-buildbot.rsa:
    external: true
  sdk_jenkins_master_username:
    external: true
  jenkins_master_password.20210721:
    external: true
  sdk_signing_private_key.gpgkey:
    external: true
  sdk_signing_public_key.gpgkey:
    external: true
  id_ns-codereview_20181212:
    external: true
  sdk_docker_config_20210719:
    external: true

configs:
  jenkins_master_username:
    file: config/jenkins_master_username
  jenkins_slave_ssh_config_20200422:
    file: conf/jenkins_slave_ssh_config

networks:
  jenkins:
